// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: feec04999c
// Version Date: Sat Mar 16 17:27:47 UTC 2019

package handlers

import (
	pb "github.com/ianfoo/gaproxy"
)

// Login implements Service.
func Login(IdentityLogin string) (*pb.LoginRequest, error) {
	request := pb.LoginRequest{
		Identity: IdentityLogin,
	}
	return &request, nil
}

// Query implements Service.
func Query(StartDateQuery string, EndDateQuery string, MetricsQuery []string, DimensionsQuery []string) (*pb.QueryRequest, error) {
	request := pb.QueryRequest{
		StartDate:  StartDateQuery,
		EndDate:    EndDateQuery,
		Metrics:    MetricsQuery,
		Dimensions: DimensionsQuery,
	}
	return &request, nil
}
