// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: feec04999c
// Version Date: Sat Mar 16 17:27:47 UTC 2019

package handlers

import (
	pb "github.com/ianfoo/gaproxy"
)

// Login implements Service.
func Login(IdentityLogin string) (*pb.LoginRequest, error) {
	request := pb.LoginRequest{
		Identity: IdentityLogin,
	}
	return &request, nil
}

// Logout implements Service.
func Logout(SessionIdLogout string) (*pb.LogoutRequest, error) {
	request := pb.LogoutRequest{
		SessionId: SessionIdLogout,
	}
	return &request, nil
}

// CheckSession implements Service.
func CheckSession(SessionIdCheckSession string) (*pb.CheckSessionRequest, error) {
	request := pb.CheckSessionRequest{
		SessionId: SessionIdCheckSession,
	}
	return &request, nil
}

// Query implements Service.
func Query(SessionIdQuery string, StartDateQuery string, EndDateQuery string, MetricsQuery []string, DimensionsQuery []string) (*pb.QueryRequest, error) {
	request := pb.QueryRequest{
		SessionId:  SessionIdQuery,
		StartDate:  StartDateQuery,
		EndDate:    EndDateQuery,
		Metrics:    MetricsQuery,
		Dimensions: DimensionsQuery,
	}
	return &request, nil
}

// Ping implements Service.
func Ping() (*pb.PingRequest, error) {
	request := pb.PingRequest{}
	return &request, nil
}
