// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: feec04999c
// Version Date: Sat Mar 16 17:27:47 UTC 2019

// Package grpc provides a gRPC client for the GAProxy service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/ianfoo/gaproxy"
	"github.com/ianfoo/gaproxy/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.GAProxyServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var loginEndpoint endpoint.Endpoint
	{
		loginEndpoint = grpctransport.NewClient(
			conn,
			"gaproxy.GAProxy",
			"Login",
			EncodeGRPCLoginRequest,
			DecodeGRPCLoginResponse,
			pb.LoginResponse{},
			clientOptions...,
		).Endpoint()
	}

	var logoutEndpoint endpoint.Endpoint
	{
		logoutEndpoint = grpctransport.NewClient(
			conn,
			"gaproxy.GAProxy",
			"Logout",
			EncodeGRPCLogoutRequest,
			DecodeGRPCLogoutResponse,
			pb.LogoutResponse{},
			clientOptions...,
		).Endpoint()
	}

	var checksessionEndpoint endpoint.Endpoint
	{
		checksessionEndpoint = grpctransport.NewClient(
			conn,
			"gaproxy.GAProxy",
			"CheckSession",
			EncodeGRPCCheckSessionRequest,
			DecodeGRPCCheckSessionResponse,
			pb.CheckSessionResponse{},
			clientOptions...,
		).Endpoint()
	}

	var queryEndpoint endpoint.Endpoint
	{
		queryEndpoint = grpctransport.NewClient(
			conn,
			"gaproxy.GAProxy",
			"Query",
			EncodeGRPCQueryRequest,
			DecodeGRPCQueryResponse,
			pb.QueryResponse{},
			clientOptions...,
		).Endpoint()
	}

	var pingEndpoint endpoint.Endpoint
	{
		pingEndpoint = grpctransport.NewClient(
			conn,
			"gaproxy.GAProxy",
			"Ping",
			EncodeGRPCPingRequest,
			DecodeGRPCPingResponse,
			pb.PingResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		LoginEndpoint:        loginEndpoint,
		LogoutEndpoint:       logoutEndpoint,
		CheckSessionEndpoint: checksessionEndpoint,
		QueryEndpoint:        queryEndpoint,
		PingEndpoint:         pingEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCLoginResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC login reply to a user-domain login response. Primarily useful in a client.
func DecodeGRPCLoginResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.LoginResponse)
	return reply, nil
}

// DecodeGRPCLogoutResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC logout reply to a user-domain logout response. Primarily useful in a client.
func DecodeGRPCLogoutResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.LogoutResponse)
	return reply, nil
}

// DecodeGRPCCheckSessionResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC checksession reply to a user-domain checksession response. Primarily useful in a client.
func DecodeGRPCCheckSessionResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.CheckSessionResponse)
	return reply, nil
}

// DecodeGRPCQueryResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC query reply to a user-domain query response. Primarily useful in a client.
func DecodeGRPCQueryResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.QueryResponse)
	return reply, nil
}

// DecodeGRPCPingResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC ping reply to a user-domain ping response. Primarily useful in a client.
func DecodeGRPCPingResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.PingResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCLoginRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain login request to a gRPC login request. Primarily useful in a client.
func EncodeGRPCLoginRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.LoginRequest)
	return req, nil
}

// EncodeGRPCLogoutRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain logout request to a gRPC logout request. Primarily useful in a client.
func EncodeGRPCLogoutRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.LogoutRequest)
	return req, nil
}

// EncodeGRPCCheckSessionRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain checksession request to a gRPC checksession request. Primarily useful in a client.
func EncodeGRPCCheckSessionRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.CheckSessionRequest)
	return req, nil
}

// EncodeGRPCQueryRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain query request to a gRPC query request. Primarily useful in a client.
func EncodeGRPCQueryRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.QueryRequest)
	return req, nil
}

// EncodeGRPCPingRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain ping request to a gRPC ping request. Primarily useful in a client.
func EncodeGRPCPingRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.PingRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
